<!DOCTYPE html>	
<html>

	<head>
		<title>My website</title>
        <link rel="stylesheet" type="text/css" href="style.css" />
	</head>

	<body>
		<div id="container" width="800">

			<div id="header">
			<h1>Welcome to my website!</h1>
			</div>
    
            <div id="content">
                <div id="nav">
				<h3>Navigation</h3>
                    <ul>
                        <li><a href="index.html">Home</a></li>
                        <li><a href="about.html">About</a></li>
                        <li><a href="01-electronicsproduction.html">Electronics Production</a></li>
                        <li><a href="02-electronicsdesign.html">Electronics Design</a></li>
                        <li><a class="selected" href="">2D CNC</a></li>
                        <li><a href="04-embeddedprog.html">Embedded Programming</aa></li>
                        <li><a href="05-mouldingcasting.html">Moulding and casting</a></li>
                        <li><a href="06-3dcnc.html">3D CNC</a></li>
                        <li><a href="07-interface_applications_prog.html">Interface Applications Programming</a></li>
						<li><a href="08-finalproj.html">Final FDFAB project</a></li>
                    </ul>
                </div>

				<div id="main">
				 
					<h1>2D CNC</h1>
					
					<h2>Example stool</h2>
					<p>
					In order to familiarise myself with the workflow of designing milled products, i followed this <a href="https://www.youtube.com/watch?v=DHrP1MunhFw">video guide</a> from autodesk on youtube.
					</p>
					
					<p>
						Firstly, i created a sketch on the xy plane and drew a center-diameter circle with radius pointed at the variable "seat_diam".
						<img src="pics/stool/stool1.jpg" alt="" width="500"> <br>
					</p>
					
					<p>
						I then made a new component and sketch, which has a parametric height variable defined by the variable "height". After that, i extruded the whole profile by the variable "wood_thickness". This allows me to easily change the design to fit any wood thickness available in the fablab at the time.
						<img src="pics/stool/stool2.jpg" alt="" width="500"> <br>
					</p>
					
					<p>
						I duplicated the leg component and rotated it 90 degrees in the z-axis.
						<img src="pics/stool/stool3.jpg" alt="" width="500"> <br>
					</p>
					
					<p>
						Instead of doing a combine-cut operation, the video manually sketched out the + shaped hole on the seat such that clearance can be easily changed should the machine need it. So that was what i did.
						<img src="pics/stool/stool4.jpg" alt="" width="500"> <br>
					</p>
					
					<p>
						This is the completed result!
						<img src="pics/stool/stool5.jpg" alt="" width="500"> <br>
						However, I needed to extract the dxf of each of the individual components, so I had to lay the pieces flat on the xy axis. Doing this also gives me a good idea of how much stock will be needed for milling.
					</p>
					
					<p>
						<iframe src="https://myhub.autodesk360.com/ue2c04282/shares/public/SH56a43QTfd62c1cd968f5ace12aa769ddaf?mode=embed" width="500" height="480" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true"  frameborder="0"></iframe>
					</p>
					
					<p>
						<img src="pics/stool/stoolmilling.jpeg" alt="" width="250">
						<img src="pics/stool/stoolcnc.jpeg" alt="" width="250"> <br>
					</p>
					
					<p>
						After sanding off the edges, I assembled the pieces to end up with this stool.
						<img src="pics/stool/stoolcompleted.jpeg" alt="" width="500"> <br>
					</p>
					
					<h2>Drone launch pad</h2>
					
					<p>
						After browsing on the internet, i found this drone launch stand that could be interesting to try out.<br>
						
						<img src="pics/dronestand/launchpad.jpg" alt="" width="500"><br>

						So, i decided that it would be interesting to make one using the 2D CNC as part of my topic assignment.
					</p>
					
					<p>
						Firstly, i drew a simple sketch of the side profile. The small bump in the lower part of the slope is to prevent the drone from sliding off.
						<img src="pics/dronestand/stand1.jpg" alt="" width="500"> <br>
						I also made this part parametric since the launch angle of the drone can vary according to different pilots.
						<img src="pics/dronestand/stand1.5.jpg" alt="" width="500">
					</p>
					
					<p>
						After a simple extrude using the variable "woodthickness",
						<img src="pics/dronestand/stand2.jpg" alt="" width="500">
					</p>
					
					<p>
						By using the move tool, I duplicated the component and moved it an arbituary amount to the right. 
						<img src="pics/dronestand/stand2.5.jpg" alt="" width="500">
					</p>
					
					<p>
						<img src="pics/dronestand/stand3.jpg" alt="" width="500">
					</p>
					
					<p>
						In order for the stand to clear the battery and the motors, I did a quick measurement of the arms. 80mm distance seems to be a good width for the stand.
						<img src="pics/dronestand/stand3.5.jpeg" alt="" width="500">
					</p>
					
					<p>
						After sketching the base dimensions,
						<img src="pics/dronestand/stand3.75.jpg" alt="" width="500">
					</p>
					
					<p>
						After moving the 2 components the appropiate distance with each other.
						<img src="pics/dronestand/stand4.jpg" alt="" width="500">
					</p>
					
					<p>
						<img src="pics/dronestand/stand5.jpg" alt="" width="500">
					</p>
					
					<p>
						Using the sketch tool, I drew a slot on the base plate and mirrored it longitudinally.
						<img src="pics/dronestand/stand6.jpg" alt="" width="500">
					</p>
					
					<p>
						After a simple extrude operation,
						<img src="pics/dronestand/stand7.jpg" alt="" width="500">
					</p>
					
					<p>
						<img src="pics/dronestand/stand8.jpg" alt="" width="500">
					</p>
					
					<p>
						Using the base plate as a tool, i cut the side plates to transfer the slots.
						<img src="pics/dronestand/stand9.jpg" alt="" width="500">
					</p>
					
					<p>
						In order to get an idea of how much stock i will need, how the parts will be arranged, and to extract the dxf files from the model, i laid the pieces flat against the stock.
						<img src="pics/dronestand/stand10.jpg" alt="" width="500">
					</p>
					
					<p>
						However, due to a directory issue, I was not able to make the dogbones in fusion360. <br>
						
						<img src="pics/dronestand/stand13.jpg" alt="" width="500">
					</p>
					
					<p>
						After consulting my teacher, i was able to redo the dogbones properly by making a new sketch, projecting the existing geometry, and extruding the profile. This is the result. <br>
						
						<img src="pics/dronestand/stand14.jpg" alt="" width="500">
					</p>
						
                </div>
                
				<div id="footer">
				Copyright &copy; Jovan Peh
				</div>
                
			</div>
                
        </div>

	</body>

</html>